name: flutter_mid_basic_exam
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  sqflite: ^2.4.1
  path: ^1.9.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.1
  image_picker: ^1.1.2
  video_player: ^2.9.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  android_intent_plus: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - image/
    - image/assets/
    - assets/
    - assets/image/
